<a href="https://colab.research.google.com/github/ajita-asthana/Node-tuts/blob/master/asthana_ajeeta_assignment06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**README**

Assignment 06

**Ajeeta Asthana**

Objects and Dataframes

##Part 1: Using DateTime module

In [ ]:
from datetime import date
Date = date.today().strftime("%m/%d/%y")

In [ ]:
import datetime
import pytz
current_time = datetime.datetime.now(pytz.timezone("US/Eastern"))

In [ ]:
print("Date: ", Date)
print("Time: ",current_time.strftime('%-I'),":",current_time.strftime('%M'), current_time.strftime('%p'), sep="", end=".")

Date:  10/25/22
Time: 11:25AM.

##Part 2: Building a class, method and objects

In [ ]:
class crypto:

  def __init__(self, name, symbol, price, circulating_supply):
    print("You have created an object of type crypto!")
    self.name = name
    self.symbol = symbol
    self.price = price
    self.circulating_supply = circulating_supply
    print("The name is ", self.name)
    print("The symbol is ", self.symbol)
    print("The price is ", self.price)
    print("The circulating supply is ", self.circulating_supply)

  def setPrice(self, price):
    self.price = price
    print("The price is ",self.price)

  def setCirculating(self, circulating_supply):
    self.circulating_supply = circulating_supply
    print("The circulating supply is ", self.circulating_supply)

  def getMarketCap(self):
    marketCap =  self.price * self.circulating_supply
    print("The market cap for cryptocurrency", self.name,"is $",marketCap)

In [ ]:
bitcoinObj = crypto("Bitcoin", "BTC", 19193.00, 19187300)

You have created an object of type crypto!
The name is  Bitcoin
The symbol is  BTC
The price is  19193.0
The circulating supply is  19187300

In [ ]:
ethereumObj = crypto("Ethereum", "ETH", 1309.74, 122373863)

You have created an object of type crypto!
The name is  Ethereum
The symbol is  ETH
The price is  1309.74
The circulating supply is  122373863

In [ ]:
dogecoinObj = crypto("Dogecoin", "DOGE", 0.05933, 132670764300)

You have created an object of type crypto!
The name is  Dogecoin
The symbol is  DOGE
The price is  0.05933
The circulating supply is  132670764300

In [ ]:
tetherObj = crypto("Tether", "USDT", 1.00, 68453108030)

You have created an object of type crypto!
The name is  Tether
The symbol is  USDT
The price is  1.0
The circulating supply is  68453108030

In [ ]:
bitcoinObj.getMarketCap()

The market cap for cryptocurrency Bitcoin is $ 368261848900.0

In [ ]:
ethereumObj.getMarketCap()

The market cap for cryptocurrency Ethereum is $ 160277943325.62

In [ ]:
dogecoinObj.getMarketCap()

The market cap for cryptocurrency Dogecoin is $ 7871356445.919

In [ ]:
tetherObj.getMarketCap()

The market cap for cryptocurrency Tether is $ 68453108030.0

##Part 3: Using pandas

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving cereal.xlsx to cereal.xlsx

In [ ]:
import pandas as pd
import io
mydataframe = pd.read_excel('cereal.xlsx', engine="openpyxl")

In [ ]:
mydataframe

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70.0,4.0,1.0,130.0,10.0,5.0,6.0,280.0,25.0,3.0,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120.0,3.0,5.0,15.0,2.0,8.0,8.0,135.0,0.0,3.0,1.0,1.00,33.983679
2,All-Bran,K,C,70.0,4.0,1.0,260.0,9.0,7.0,5.0,320.0,25.0,3.0,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50.0,4.0,0.0,140.0,14.0,8.0,0.0,330.0,25.0,3.0,1.0,0.50,93.704912
4,Almond Delight,R,C,110.0,2.0,2.0,200.0,1.0,14.0,8.0,-1.0,25.0,3.0,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110.0,2.0,1.0,250.0,0.0,21.0,3.0,60.0,25.0,3.0,1.0,0.75,39.106174
73,Trix,G,C,110.0,1.0,1.0,140.0,0.0,13.0,12.0,25.0,25.0,2.0,1.0,1.00,27.753301
74,Wheat Chex,R,C,100.0,3.0,1.0,230.0,3.0,17.0,3.0,115.0,25.0,1.0,1.0,0.67,49.787445
75,Wheaties,G,C,100.0,3.0,1.0,200.0,3.0,17.0,3.0,110.0,25.0,1.0,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110.0,2.0,1.0,200.0,1.0,16.0,8.0,60.0,25.0,1.0,1.0,0.75,36.187559

In [ ]:
mydataframe.head(5)

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70.0,4.0,1.0,130.0,10.0,5.0,6.0,280.0,25.0,3.0,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120.0,3.0,5.0,15.0,2.0,8.0,8.0,135.0,0.0,3.0,1.0,1.00,33.983679
2,All-Bran,K,C,70.0,4.0,1.0,260.0,9.0,7.0,5.0,320.0,25.0,3.0,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50.0,4.0,0.0,140.0,14.0,8.0,0.0,330.0,25.0,3.0,1.0,0.50,93.704912
4,Almond Delight,R,C,110.0,2.0,2.0,200.0,1.0,14.0,8.0,-1.0,25.0,3.0,1.0,0.75,34.384843

In [ ]:
mydataframe.tail(5)

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
72,Triples,G,C,110.0,2.0,1.0,250.0,0.0,21.0,3.0,60.0,25.0,3.0,1.0,0.75,39.106174
73,Trix,G,C,110.0,1.0,1.0,140.0,0.0,13.0,12.0,25.0,25.0,2.0,1.0,1.00,27.753301
74,Wheat Chex,R,C,100.0,3.0,1.0,230.0,3.0,17.0,3.0,115.0,25.0,1.0,1.0,0.67,49.787445
75,Wheaties,G,C,100.0,3.0,1.0,200.0,3.0,17.0,3.0,110.0,25.0,1.0,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110.0,2.0,1.0,200.0,1.0,16.0,8.0,60.0,25.0,1.0,1.0,0.75,36.187559

In [ ]:
mydataframe.shape

(77, 16)

In [ ]:
mydataframe.columns

Index(['name', 'mfr', 'type', 'calories', 'protein', 'fat', 'sodium', 'fiber',
       'carbo', 'sugars', 'potass', 'vitamins', 'shelf', 'weight', 'cups',
       'rating'],
      dtype='object')

In [ ]:
mydataframe.dtypes

name         object
mfr          object
type         object
calories    float64
protein     float64
fat         float64
sodium      float64
fiber       float64
carbo       float64
sugars      float64
potass      float64
vitamins    float64
shelf       float64
weight      float64
cups        float64
rating      float64
dtype: object

In [ ]:
mydataframe.info

<bound method DataFrame.info of                          name mfr type  calories  protein  fat  sodium  fiber  \
0                   100% Bran   N    C      70.0      4.0  1.0   130.0   10.0
1           100% Natural Bran   Q    C     120.0      3.0  5.0    15.0    2.0
2                    All-Bran   K    C      70.0      4.0  1.0   260.0    9.0
3   All-Bran with Extra Fiber   K    C      50.0      4.0  0.0   140.0   14.0
4              Almond Delight   R    C     110.0      2.0  2.0   200.0    1.0
..                        ...  ..  ...       ...      ...  ...     ...    ...
72                    Triples   G    C     110.0      2.0  1.0   250.0    0.0
73                       Trix   G    C     110.0      1.0  1.0   140.0    0.0
74                 Wheat Chex   R    C     100.0      3.0  1.0   230.0    3.0
75                   Wheaties   G    C     100.0      3.0  1.0   200.0    3.0
76        Wheaties Honey Gold   G    C     110.0      2.0  1.0   200.0    1.0

    carbo  sugars  potass  vitamins  shelf  weight  cups     rating
0     5.0     6.0   280.0      25.0    3.0     1.0  0.33  68.402973
1     8.0     8.0   135.0       0.0    3.0     1.0  1.00  33.983679
2     7.0     5.0   320.0      25.0    3.0     1.0  0.33  59.425505
3     8.0     0.0   330.0      25.0    3.0     1.0  0.50  93.704912
4    14.0     8.0    -1.0      25.0    3.0     1.0  0.75  34.384843
..    ...     ...     ...       ...    ...     ...   ...        ...
72   21.0     3.0    60.0      25.0    3.0     1.0  0.75  39.106174
73   13.0    12.0    25.0      25.0    2.0     1.0  1.00  27.753301
74   17.0     3.0   115.0      25.0    1.0     1.0  0.67  49.787445
75   17.0     3.0   110.0      25.0    1.0     1.0  1.00  51.592193
76   16.0     8.0    60.0      25.0    1.0     1.0  0.75  36.187559

[77 rows x 16 columns]>

In [ ]:
mydataframe.nsmallest(3,'calories')

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
3,All-Bran with Extra Fiber,K,C,50.0,4.0,0.0,140.0,14.0,8.0,0.0,330.0,25.0,3.0,1.0,0.5,93.704912
54,Puffed Rice,Q,C,50.0,1.0,0.0,0.0,0.0,13.0,0.0,15.0,0.0,3.0,0.5,1.0,60.756112
55,Puffed Wheat,Q,C,50.0,2.0,0.0,0.0,1.0,10.0,0.0,50.0,0.0,3.0,0.5,1.0,63.005645

In [ ]:
mydataframe.nlargest(3,'calories')

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
46,Mueslix Crispy Blend,K,C,160.0,3.0,2.0,150.0,3.0,17.0,13.0,160.0,25.0,3.0,1.5,0.67,30.313351
44,Muesli Raisins; Dates; & Almonds,R,C,150.0,4.0,3.0,95.0,3.0,16.0,11.0,170.0,25.0,3.0,1.0,1.00,37.136863
45,Muesli Raisins; Peaches; & Pecans,R,C,150.0,4.0,3.0,150.0,3.0,16.0,11.0,170.0,25.0,3.0,1.0,1.00,34.139765

In [ ]:
mydataframe.sample()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
62,Rice Krispies,K,C,110.0,2.0,0.0,290.0,0.0,22.0,3.0,35.0,25.0,1.0,1.0,1.0,40.560159

In [ ]:
mydataframe.describe()

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
count,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000
mean,106.883117,2.545455,1.012987,159.675325,2.151948,14.597403,6.922078,96.077922,28.246753,2.207792,1.029610,0.821039,42.665705
std,19.484119,1.094790,1.006473,83.832295,2.383364,4.278956,4.444885,71.286813,22.342523,0.832524,0.150477,0.232716,14.047289
min,50.000000,1.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,-1.000000,0.000000,1.000000,0.500000,0.250000,18.042851
25%,100.000000,2.000000,0.000000,130.000000,1.000000,12.000000,3.000000,40.000000,25.000000,1.000000,1.000000,0.670000,33.174094
50%,110.000000,3.000000,1.000000,180.000000,2.000000,14.000000,7.000000,90.000000,25.000000,2.000000,1.000000,0.750000,40.400208
75%,110.000000,3.000000,2.000000,210.000000,3.000000,17.000000,11.000000,120.000000,25.000000,3.000000,1.000000,1.000000,50.828392
max,160.000000,6.000000,5.000000,320.000000,14.000000,23.000000,15.000000,330.000000,100.000000,3.000000,1.500000,1.500000,93.704912

In [ ]:
mydataframe.sort_values('carbo')

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
57,Quaker Oatmeal,Q,H,100.0,5.0,2.0,0.0,2.7,-1.0,-1.0,110.0,0.0,1.0,1.00,0.67,50.828392
0,100% Bran,N,C,70.0,4.0,1.0,130.0,10.0,5.0,6.0,280.0,25.0,3.0,1.00,0.33,68.402973
2,All-Bran,K,C,70.0,4.0,1.0,260.0,9.0,7.0,5.0,320.0,25.0,3.0,1.00,0.33,59.425505
1,100% Natural Bran,Q,C,120.0,3.0,5.0,15.0,2.0,8.0,8.0,135.0,0.0,3.0,1.00,1.00,33.983679
3,All-Bran with Extra Fiber,K,C,50.0,4.0,0.0,140.0,14.0,8.0,0.0,330.0,25.0,3.0,1.00,0.50,93.704912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,Kix,G,C,110.0,2.0,1.0,260.0,0.0,21.0,3.0,40.0,25.0,2.0,1.00,1.50,39.241114
49,Nutri-Grain Almond-Raisin,K,C,140.0,3.0,2.0,220.0,3.0,21.0,7.0,130.0,25.0,3.0,1.33,0.67,40.692320
15,Corn Chex,R,C,110.0,2.0,0.0,280.0,0.0,22.0,3.0,25.0,25.0,1.0,1.00,1.00,41.445019
62,Rice Krispies,K,C,110.0,2.0,0.0,290.0,0.0,22.0,3.0,35.0,25.0,1.0,1.00,1.00,40.560159
61,Rice Chex,R,C,110.0,1.0,0.0,240.0,0.0,23.0,2.0,30.0,25.0,1.0,1.00,1.13,41.998933